### ISSUE TITLE
Any charge in version 2.3.4 fails with an SSL exception

### ISSUE THREAD

**Issue by panzerfausten** [conekta/conekta-python#26]
Hi guys, me again.

So I noticed you updated the lib to 2.3.4 and now everytime I try to charge with credit card or oxxo I get the following error:

> 127.0.0.1 - - [09/May/2017 11:54:40] "POST /api/orders HTTP/1.1" 500 -
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
>     return self.wsgi_app(environ, start_response)
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
>     response = self.make_response(self.handle_exception(e))
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/usr/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/home/darien/dev/panzer/projects/piruet/main.py", line 125, in order
>     _result = O.createOrder(_order)
>   File "/home/darien/dev/panzer/projects/piruet/models/Orders.py", line 100, in createOrder
>     _result = _CC.chargeCreditDebit(_package)
>   File "/home/darien/dev/panzer/projects/piruet/models/ConektaCharge.py", line 85, in chargeCreditDebit
>     charge = conekta.Charge.create(_payment)
>   File "build/bdist.linux-x86_64/egg/conekta/__init__.py", line 201, in create
>     return cls(cls.load_url(endpoint, method='POST', params=params, api_key=api_key))
>   File "build/bdist.linux-x86_64/egg/conekta/__init__.py", line 112, in load_url
>     response = cls.build_http_request(method, path, params, _api_key = api_key)
>   File "build/bdist.linux-x86_64/egg/conekta/__init__.py", line 84, in build_http_request
>     headers, body = request(absolute_url, method, headers=HEADERS, body=json.dumps(params))
>   File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1609, in request
>     (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
>   File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1351, in _request
>     (response, content) = self._conn_request(conn, request_uri, method, body, headers)
>   File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1272, in _conn_request
>     conn.connect()
>   File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 1036, in connect
>     self.disable_ssl_certificate_validation, self.ca_certs)
>   File "/usr/lib/python2.7/site-packages/httplib2/__init__.py", line 80, in _ssl_wrap_socket
>     cert_reqs=cert_reqs, ca_certs=ca_certs)
>   File "/usr/lib64/python2.7/ssl.py", line 941, in wrap_socket
>     ciphers=ciphers)
>   File "/usr/lib64/python2.7/ssl.py", line 548, in __init__
>     self._context.load_verify_locations(cafile=cafile, capath=capath)
> IOError: [Errno 20] Not a directory
> 

Now I am not so sure what's going on here but maybe the conekta lib is trying to use some missing SSL certificate from Python stock libraries. Could you take a look at this?

Bests,
-Darien.

**Comment by panzerfausten** [comment]
The problem is that the certificate (ca_bundle.crt) packed with the library is not available once the egg is installed.

Then Httplib2 looks for the file at the following path:

> /usr/lib/python2.7/site-packages/conekta-2.3.4-py2.7.egg/conekta/ssl_data/ca_bundle.crt

Httplib2 crashes (and catches fire) because can't read the file.

A workaround I used is to extract the egg at: 

> /usr/lib/python2.7/site-packages/conekta-2.3.4-py2.7.egg

and put it in the same path (a folder called "conekta-2.3.4-py2.7.egg" with the original content in it). Works like a charm.

I still don't know if the error is caused by my O.S. but I am glad it's working now.

-Darien.
