### ISSUE TITLE
AttributeError: module 'conekta' has no attribute 'Order'

### ISSUE THREAD

**Issue by BrandoIsNotASword** [conekta/conekta-python#48]
I'm trying to integrate Conekta in my webpage. I'm using Python 3 as my backend programming language, but when I import the module, I receive an error that the attribute Order nor ConektaError, as the document example provides, doesn't exist.

Here is my code:
```
import conekta

conekta.api_key = 'api_key' # api key development
conekta.api_version = '2.0.0'
conekta.locale = 'es'

try:
  order = conekta.Order.create({
      'line_items': [{
          'name': 'Tacos',
          'unit_price': 1000,
          'quantity': 120
      }],
      'currency': 'MXN',
      'customer_info': {
          'name': 'Brando Pérez Pacheco',
          'phone': '9981231289',
          'email': 'brando.perez.pacheco@gmail.com',
      },
      'charges': [{
          'payment_method': {
              'type': 'card',
              'token_id': 'tok_test_visa_4242'
          }
      }]

  })

  print(order)

except conekta.ConektaError as e:
  print(e.message)
```

This is the error:
```
Traceback (most recent call last):                                                                                                                  
  File "conekta.py", line 1, in <module>                                                                                                            
    import conekta                                                                                                                                  
  File "/home/Brandopp/mysite/conekta.py", line 8, in <module>                                                                                      
    conekta.Order.create({                                                                                                                          
AttributeError: module 'conekta' has no attribute 'Order'                                                                                           
03:32 ~/mysite $ python3 conekta.py                                                                                                                 
Traceback (most recent call last):                                                                                                                  
  File "conekta.py", line 1, in <module>                                                                                                            
    import conekta                                                                                                                                  
  File "/home/Brandopp/mysite/conekta.py", line 8, in <module>                                                                                      
    conekta.Order.create({                                                                                                                          
AttributeError: module 'conekta' has no attribute 'Order'```

**Comment by leofischer** [comment]
Hi @BrandoIsNotASword,

It doesn't seem like it is importing `conekta` properly, or maybe something is overwriting it.  What version of conekta-python are you using, and can you provide an example of how you are running your console?  Additionally how are you installing the conekta library, are you using pip3?  For example when I run you code I get something this:

```python
root@a038f18ef456:/app# python
Python 3.8.0 (default, Nov 23 2019, 05:36:56) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import conekta
>>> 
>>> conekta.api_key = 'key_ZLy4aP2szht1HqzkCezDEA' # api key development
>>> conekta.api_version = '2.0.0'
>>> conekta.locale = 'es'
>>> 
>>> try:
...   order = conekta.Order.create({
...       'line_items': [{
...           'name': 'Tacos',
...           'unit_price': 1000,
...           'quantity': 120
...       }],
...       'currency': 'MXN',
...       'customer_info': {
...           'name': 'Brando Pérez Pacheco',
...           'phone': '9981231289',
...           'email': 'brando.perez.pacheco@gmail.com',
...       },
...       'charges': [{
...           'payment_method': {
...               'type': 'card',
...               'token_id': 'tok_test_visa_4242'
...           }
...       }]
...   })
...   print(order.__dict__)
... except conekta.ConektaError as e:
...   print(e.message)
... 

{'id': 'ord_2mjhrm7MUtryMuTpX', 'livemode': False, 'amount': 120000, 'currency': 'MXN', 'payment_status': 'paid', 'amount_refunded': 0, 'customer_info': <conekta.CustomerInfo object at 0x7f5769e81220>, 'object': 'order', 'metadata': {}, 'created_at': 1574795018, 'updated_at': 1574795018, 'line_items': [<conekta.LineItem object at 0x7f5769e52e50>], 'charges': [<conekta.Charge object at 0x7f5768c82730>], 'tax_lines': [], 'shipping_lines': [], 'discount_lines': []}
>>> 
```

**Comment by leofischer** [comment]
Voy a cerrar este issue de momento, nos pueden contactar si vuelva a ocurrir
